# Generated by Django 2.2.4 on 2019-08-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sfile',
            field=models.FileField(default='', editable=False, upload_to='files/'),
        ),
    ]
